about/urls.py
from django.urls import path
from .views import AboutTemplateView
app_name = 'about'
urlpatterns = [
    path('', AboutTemplateView.as_view(), name='about')
]

account/urls.py
from django.urls import path
from .views import detail, login, register, logout, addresses
app_name = 'account'

urlpatterns = [    
    path('detail/', detail, name="detail"),
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('register/', register, name="register"),
    path('addresses/', addresses, name="addresses"),
    path('addresses/delete/<int:pk>', addresses, name="addresses"),

]

home/urls.py
from django.urls import path
from .views import HomeTemplateView

app_name = 'home'

urlpatterns = [
    path('', HomeTemplateView.as_view(), name="home"),
]

journal/urls.py
from django.urls import path
from .views import journal_view
app_name = 'journal'

urlpatterns = [
    path('', journal_view, name='journal')
]

about/models.py
from django.db import models

# Create your models here.

account/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser, User


class UserInfo(AbstractUser):

    groups = None
    user_permissions = None

class UserAddress(models.Model):

    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20, null=True, blank=True)
    company = models.CharField(max_length=100, null=True, blank=True)
    address1 = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100, null=True, blank=True)
    zipcode = models.CharField(max_length=10)
    country = models.CharField(max_length=100)
    default = models.BooleanField()

account/forms.py
from django import forms
from .models import UserInfo


class RegisterForm(forms.Form):

    first_name = forms.CharField(max_length=100, label='',
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(max_length=100, label='',
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    username = forms.CharField(max_length=100, label='',
                               widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    email = forms.EmailField(label='',
                             widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    password1 = forms.CharField(
        max_length=100, label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(
        max_length=100, label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Confirmm Password'}))

    def clean_email(self):
        if UserInfo.objects.filter(email=self.cleaned_data['email']).exists():
            raise forms.ValidationError("This email already exists")
        return self.cleaned_data['email']

    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            raise forms.ValidationError("Password doesn't match")
        return self.cleaned_data['password2']


class LoginForm(forms.Form):

    username = forms.CharField(label='',
                               widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(
        max_length=100, label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))

    # def clean_email(self):
    #     if not UserInfo.objects.filter(email= self.cleaned_data['email']).exists():
    #         raise forms.ValidationError("Email Not Found")
    #     return self.cleaned_data['email']


class AddressForm(forms.Form):

    first_name = forms.CharField(max_length=100, label='',
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(max_length=100, label='',
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    company = forms.CharField(max_length=100, label='',
                              widget=forms.TextInput(attrs={'placeholder': 'Company'}))
    phone = forms.CharField(max_length=100, label='',
                            widget=forms.TextInput(attrs={'placeholder': 'Phone'}))
    address1 = forms.CharField(max_length=100, label='',
                               widget=forms.TextInput(attrs={'placeholder': 'Address 1'}))
    address2 = forms.CharField(max_length=100, label='',
                               widget=forms.TextInput(attrs={'placeholder': 'Address 2'}))
    zipcode = forms.CharField(max_length=100, label='',
                              widget=forms.TextInput(attrs={'placeholder': 'Zip Code'}))
    country = forms.CharField(max_length=100, label='',
                              widget=forms.TextInput(attrs={'placeholder': 'Country'}))
    # default = forms.BooleanField(
    #     widget=forms.NullBooleanSelect(attrs={'id': 'default-check'}))
    default = forms.TypedChoiceField(coerce=lambda x: x == 'True',
                                     choices=((False, 'No'), (True, 'Yes')), widget=forms.NullBooleanSelect(attrs={'id': 'default-check'}))

about/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.

class AboutTemplateView(TemplateView):
    template_name = "templates/about.html"

account/views.py
from .models import UserAddress
from .forms import AddressForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from django.views.generic import TemplateView
from .forms import RegisterForm, LoginForm
from .models import UserInfo
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.contrib.auth.decorators import login_required


def logout(request):
    dj_logout(request)
    return redirect(reverse_lazy('account:login'))


def login(request):

    if request.method == "GET":
        form = LoginForm()
    elif request.method == "POST":
        print("IN POST")
        form = LoginForm(request.POST)
        if form.is_valid():
            print("VALIDATED")

            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            print(f'Username: {username}, pass: {password}')

            user = authenticate(
                username=username,
                password=password
            )
            print(user)
            if user:
                print(f"LOGGED IN AS {user.first_name}")
                dj_login(request, user)
                return redirect(reverse_lazy('account:detail'))
            else:
                print("Credential dont match")

    return render(request, 'templates/login.html', {'form': form})


def register(request):
    if request.method == "GET":
        form = RegisterForm()

    elif request.method == "POST":
        form = RegisterForm(request.POST)

        if form.is_valid():
            user = UserInfo(
                username=form.cleaned_data['username'],
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                email=form.cleaned_data['email'],
                password=form.cleaned_data['password1'],
            )
            # user.set_password(form.cleaned_data['password1'])
            user.set_password(form.cleaned_data['password1'])
            user.save()

            return redirect(reverse_lazy('account:login'))

    return render(request, 'templates/register.html', {'form': form})


@login_required(login_url=reverse_lazy('account:login'))
def detail(request):
    user = request.user
    context = {
        'user': user
    }
    return render(request, 'templates/account.html', context)


@login_required(login_url=reverse_lazy('account:login'))
def addresses(request, pk=None):
    if request.method == "GET":
        if pk:
            address = UserAddress.objects.get(id=pk)
            address.delete()
            return redirect(reverse_lazy('account:addresses'))
        else:
            form = AddressForm()
            data = UserAddress.objects.all()

            context = {
                'form': form,
                'data': data
            }

            return render(request, 'templates/addresses.html', context)

    elif request.method == "POST":
        form = AddressForm(request.POST)
        if form.is_valid():
            address = UserAddress(
                user=request.user,
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                phone=form.cleaned_data['phone'],
                address1=form.cleaned_data['address1'],
                address2=form.cleaned_data['address2'],
                zipcode=form.cleaned_data['zipcode'],
                country=form.cleaned_data['country'],
                default=form.cleaned_data['default'],
            )
            # user.set_password(form.cleaned_data['password1'])
            address.save()

        return(redirect(reverse_lazy('account:addresses')))

journal/views.py
from django.shortcuts import render

# Create your views here.

def journal_view(request):

    return render(request, 'templates/journal.html')

templates/about.html
{% extends "base.html" %}
{% load static %}
{% block title %}
About
{% endblock title %}


{% block content %}
<!-----------------------------------------About--------------------------------->
<div class="about">
    <div class="about-head">
        ABOUT
    </div>
    <div class="about-img">
        <img src="{% static 'images/about1.jpg'%}" alt="">
        <img src="{% static 'images/about2.jpg'%}" alt="">
    </div>
    <div class="about-desc">
        <p>
            <strong>POGCRAZY</strong> is a contemporary ready-to-wear label that aims to offer a minimalist wardrobe focused on clean cuts and impeccable details to strong sophisticated women.
        </p>
        <p>
            At the centre of Bouguessa is an ethos of minimalist sophistication and feminine elegance. Merging global trends and contemporary classics inspired by art, architecture and modern design, the signature silhouettes lie in highly modern cuts, bold lines, and geometric precision.
        </p>
        <p>
            <strong>POGCRAZY</strong> was founded in Apple by Banana in 2021. From her studio in Dubai Design District, she designs 3 collections a year.
        </p>
        <p>
            Faiza’s first encounter with garment making took place during her early years while spending time with her grandmother who was a seamstress herself, and who taught her the basics of knighting and sewing. Her passion led her to take numerous internships in tailor shops while studying English literature in university. Through these internships she learned the basics of pattern making and developed an understanding for fabric characteristics.
        </p>
    </div>
    <div class="about-img">
        <img src="{% static 'images/about3.jpg'%}" alt="">
        <img src="{% static 'images/about4.jpg'%}" alt="">
    </div>
</div>



{% endblock content %}

{% block scripts %}
<script src="{% static 'scripts/cart.js' %}"></script>
<script src="{% static 'scripts/mobilemenu.js' %}"></script>
{% endblock scripts %}

templates/account.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Account
{% endblock title %}


{% block content %}
    <!-----------------------------------------Account--------------------------------->


    <div class="account">
        <div class="account-welcome">
            <a href="{% url 'account:logout' %}">LOGOUT</a>
            <h3>MY ACCOUNT</h3>
            <p>Welcome back, {{ user.username  }}!</p>
        </div>
        <div class="account-orders">
            <div class="account-title">
                MY ORDERS
            </div>
            <div class="account-orders-orders">
                You haven't placed any orders yet
            </div>
        </div>
        <div class="account-primary-address">
            <div class="account-title">
                PRIMARY ADDRESS
            </div>
            <div class="address">
                <p id="address-name">{{user.first_name}} {{user.last_name}}</p>
                <p>Address1</p>
                <p>Address2</p>
                <p>Zipcode City Code</p>
                <p>Country</p>
                <button class='address-btn' onclick="location.href=`{% url 'account:addresses' %}`;">EDIT ADDRESSES</button>
            </div>
        </div>
    </div>
{% endblock content %}

{% block scripts %}
    <script src="{% static 'scripts/login.js' %}"></script>
    <script src="{% static 'scripts/cart.js' %}"></script>
    <script src="{% static 'scripts/mobilemenu.js' %}"></script>
{% endblock scripts %}

templates/addresses.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Account
{% endblock title %}


{% block content %}
<!-----------------------------------------Addresses--------------------------------->
<div class="form-container">
    <div class="address-form login-form">
        <div id="form-btn">
            <span></span>
            <span></span>
        </div>
        <h2>ADD A NEW ADDRESS</h2>
        <h3>Please fill the information below:</h3>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">ADD A NEW ADDRESS</button>
        </form>
    </div>
</div>

<!-- <div id="mobile-overlay" class="hidden"></div> -->
<div class="add-ress">
    <div class="back"><a href="{% url 'account:detail' %}">&lt;&nbsp;&nbsp;BACK TO ACCOUNT</a></div>
    <h2>MY ADDRESSES</h2>
    <button>ADD A NEW ADDRESS</button>
</div>
<div class="addresses">
    {% for d in data %}
    <div class="address">
        <div class="address-head">
            {% if d.default%}
            DEFAULT ADDRESS
            {% else %}
            Address {{d.id}}
            {% endif %}
        </div>
        <div class="address-body">
            <p id="address-name">{{d.first_name}} {{d.last_name}}</p>
            <p>{{ d.address1 }}</p>
            {% if d.address2 %}
            <p>{{ d.address2 }}</p>
            {% endif %}
            <p>{{d.zipcode}}</p>
            <p>{{d.country}}</p>
            <div class="edit">
                <a href="" class="address-edit" id='edit{{ d.id }}'>Edit</a>
                &nbsp;&nbsp;&nbsp;
                <a href="{% url 'account:addresses' d.id %}" id='delete'>Delete</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

{% block scripts %}
<script src="{% static 'scripts/cart.js' %}"></script>
<script src="{% static 'scripts/mobilemenu.js' %}"></script>
<script src="{% static 'scripts/addresses.js' %}"></script>
{% endblock scripts %}

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}  {% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
</head>

<body>
    

    <!---------------------------------Navigation---------------------------------------->
    <nav>
        <div id="hamburger-menu">
            <span></span>
            <span></span>
            <span></span>
        </div>
        <li class="nav-bar">
            <ul class="nav-item"><a href="#">SHOP</a></ul>
            <ul class="nav-item"><a href="#">COLLECTIONS</a></ul>
            <ul class="nav-item"><a href="{% url 'about:about' %}">ABOUT</a></ul>
            <ul class="nav-item"><a href="{% url 'journal:journal' %}">JOURNAL</a></ul>
        </li>
        <div class="brand">
            <span><a href="{% url 'home:home' %}">POGCRAZY</a></span>
        </div>
        <div class="nav-opt">

            <div class="opt-item" id="wishlist">
                <i class="fal fa-heart"></i>
            </div>
            <div class="opt-item" id="account">
                <a href="{% url 'account:detail' %}"><i class="fal fa-user"></i></a>
            </div>
            <div class="opt-item" id="search">
                <i class="fal fa-search"></i>
            </div>
            <div class="opt-item" id="cart">
                <i class="fal fa-shopping-cart"></i>
            </div>
        </div>
    </nav>

    <!----------------------------------------------Mobile Menu----------------------------------------------->
    <div id="mobile-overlay" class="hidden"></div>
    <div id="mobile-menu" class="hidden">
        <div id="mobile-btn">
            <span></span>
            <span></span>
        </div>
        <div id="mobile-opt">
            <div class="mobile-opt"><a href="#">SHOP</a> +</div>
            <div class="mobile-opt"><a href="#">COLLECTIONS</a> +</div>
            <div class="mobile-opt"><a href="{% url 'about:about' %}">ABOUT</a></div>
            <div class="mobile-opt"><a href="{% url 'journal:journal' %}">JOURNAL</a></div>
        </div>
        <div id="mobile-opt-extra">
            <div class="mobile-opt-extra">Retailers</div>
            <div class="mobile-opt-extra">Contact</div>
            <div class="mobile-opt-extra">Account</div>
        </div>
        <div id="mobile-menu-footer">
            <div class="mobile-menu-socials"><i class="fab fa-facebook-f"></i></div>
            <div class="mobile-menu-socials"><i class="fab fa-instagram"></i></div>
            <div class="mobile-menu-socials"><i class="fab fa-pinterest-p"></i></div>
            <div class="mobile-menu-socials"><i class="fab fa-youtube"></i></div>
        </div>
    </div>

    <!--------------------------------------------------------Cart------------------------------------------------>

    <div class="cart">
        <div class="cart-head">
            <span>CART</span>
            <div class="cart-head-button">
                <span></span>
                <span></span>
            </div>
        </div>

        <div class="cart-body">

        </div>
    </div>

    {% block content %}

    {% endblock content %}

    <!-----------------------------------------Footer----------------------------------->

    <footer>
        <div class="insta-cover">
            <div class="insta-cover-img" >
                <div class="insta-cover-overlay">
                    <i class="fab fa-instagram"></i>
                </div>
            </div>
            <div class="insta-cover-img">
                <div class="insta-cover-overlay">
                    <i class="fab fa-instagram"></i>
                </div>
            </div>
            <div class="insta-cover-img">
                <div class="insta-cover-overlay">
                    <i class="fab fa-instagram"></i>
                </div>
            </div>
            <div class="insta-cover-img">
                <div class="insta-cover-overlay">
                    <i class="fab fa-instagram"></i>
                </div>
            </div>
            <div class="insta-cover-img">
                <div class="insta-cover-overlay">
                    <i class="fab fa-instagram"></i>
                </div>
            </div>
            
            

        </div>
        <div class="overview">

            <div class="overview-menu">
                <p class = "overview-head">
                    SHOP MENU
                </p>
                <ul class= "overview-list">
                    <li class="overview-list-item"><a href="#">Coats & Long Jackets</a> </li>
                    <li class="overview-list-item"><a href="#">Skirts</a> </li>
                    <li class="overview-list-item"><a href="#">Pants</a> </li>
                    <li class="overview-list-item"><a href="#">Dresses</a> </li>
                    <li class="overview-list-item"><a href="#">Tops</a> </li>
                    <li class="overview-list-item"><a href="#">Accessories</a> </li>
                </ul>
            </div>

            <div class="overview-help">
                <p class = "overview-head">
                    HELP
                </p>
                <ul class= "overview-list">
                    <li class="overview-list-item"><a href="">Contact</a> </li>
                    <li class="overview-list-item"><a href="">My Account</a></li>
                    <li class="overview-list-item"><a href="">Terms & Condition</a></li>
                    <li class="overview-list-item"><a href="">Retailers</a></li>
                    <li class="overview-list-item"><a href="">Privacy Policy</a></li>             
                </ul>
            </div>
            <div class="overview-newsletter">
                <p class = "overview-head">
                    NEWSLETTER
                </p>
                <p class="overview-list-item">
                    Sign up for 10% off your next order*
                </p>
                <form method="POST">
                    <input type="email" name="email" placeholder="Enter your email address" autocomplete="off">
                    <button type="submit">SUBSCRIBE</button>
                </form>

            </div>
        </div>

        <div class="socials">
            <div class="footer-socials"><i class="fab fa-facebook-f"></i></div>
            <div class="footer-socials"><i class="fab fa-instagram"></i></div>
            <div class="footer-socials"><i class="fab fa-pinterest-p"></i></div>
            <div class="footer-socials"><i class="fab fa-youtube"></i></div>
        </div>
        <div class="footer">
            <div class="copyright">
                <p>&#169; 2021 POGCRAZY</p>
            </div>
            <div class="payment">
                <i class="fab fa-apple-pay"></i>
                <i class="fab fa-cc-paypal"></i>
                <i class="fab fa-cc-visa"></i>
                <i class="fab fa-cc-mastercard"></i>
            </div>
        </div>


    </footer>
    <script>
        const instaCovers = document.getElementsByClassName('insta-cover-img');
        for (let i = 1; i < instaCovers.length+1; i++){
            instaCovers[i-1].style.background = `url(static/images/insta-${i}.jpg) center center no-repeat`;
            // instaCovers[i-1].style.background = `url({% static 'images/insta-' %}) center center no-repeat`;

            instaCovers[i-1].style.backgroundSize = 'contain';


        }

    </script>
    {% block scripts %}

    {% endblock scripts %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}


{% block title %}
    Pogcrazy
{% endblock title %}


{% block content %}
    <!-----------------------------------------Banner--------------------------------->

    <div class="banner">
        <div class="overlay">
            <div class="banner-info">
                <h2>SIGNATURE LINE</h2>
                <p>Discover new styles added to our signature line</p>
                <a href="#">Discover the collection</a>
            </div>
        </div>
    </div>

    <!-----------------------------------------Collection Promo 1----------------------------->

    <div class="collection-promo">
        <div class="promo-1">
            <h2>ECO-CONSCIOUS SIGNATURE LINE</h2>
            <img src="{% static 'images/promo1.jpg' %}" alt="ECO-CONSCIOUS SIGNATURE LINE 1">
            <p>The third launch of signature line continues a pledge to sustainability at the forefront by focusing on consciousness for a smarter approach to fashion</p>
            <a href="#">Discover the collection</a>
        </div>
        <div class="promo-2">
            <img src="{% static 'images/promo2.jpg' %}" alt="ECO-CONSCIOUS SIGNATURE LINE 2">
        </div>
    </div>

    <!-----------------------------------------Collection Showcase----------------------------->
    <div class="collection-showcase fade-in">
        <div class="collection-showcase-card" id="card1" onclick="location.href='#';">
            <img src="{% static 'images/card11.jpg' %}" alt="">
            <h2>COTTON PUFFED SLEEVES SHIRT DRESS</h2>
            <span class="price">$655</span>
        </div>
        <div class="collection-showcase-card" id="card2" onclick="location.href='#';">
            <img src="{% static 'images/card21.jpg' %}" alt="" >
            <h2>SIDE PLEATS LONG JACKET</h2>
            <span class="price">$853</span>
        </div>
        <div class="collection-showcase-card" id="card3" onclick="location.href='#';">
            <img src="{% static 'images/card31.jpg' %}" alt="" >
            <h2>COTTON KAFTAN DRESS</h2>
            <span class="price">$589</span>
        </div>
        <div class="collection-showcase-card" id="card4" onclick="location.href='#';">
            <img src="{% static 'images/card41.jpg' %}" alt="" >
            <h2>CONTRASTED LOOSE LONG CARDIGAN</h2>
            <span class="price">$671</span>
        </div>

    </div>

    <!-----------------------------------------Shop Collection Button----------------------------->
    <div class="shop-collection">
        <a href="#">SHOP THE COLLECTION</a>
    </div>


    <!--------------------------------------------Banner------------------------------------->
    <div class="showcase-banner">
        <div class="overlay">
            <h2>SPRING SUMMER 2021</h2>
            <a href="#">Discover the collection</a>                
        </div>

    </div>

    <!-----------------------------------------Collection Promo 1----------------------------->

    <div class="collection-promo">
        <div class="promo-3">
            <h2>ECO-CONSCIOUS SIGNATURE LINE</h2>
            <img src="{% static 'images/promo3.jpg' %}" alt="ECO-CONSCIOUS SIGNATURE LINE 1">
            <p>The Bouguessa FW21 collection is about reinventing wardrobe classics for the modern-day wearer.</p>
            <a href="#">Discover the collection</a>
        </div>
        <div class="promo-4">
            <!-- <img src="./images/promo4.jpg" alt="ECO-CONSCIOUS SIGNATURE LINE 2"> -->
        </div>
    </div>
    

    <!-------------------------------------------Collection Carousel------------------------>
    <div class="collection-carousel">

    
        <div class ="collection-carousel-title">
            SPRING-SUMMER 2021
        </div>
        <div class=collection-carousel-main>
            <div class="next-button left-button">
                <i class="far fa-chevron-left"></i>
            </div>
            <div class="collection-carousel-cards">
                <div class="bag">
                    <div class="collection-carousel-card" id="1" data-pos="1" onclick="location.href='#';">
                        <img src="{% static 'images/card11.jpg' %}" alt="">
                        <h2>COTTON PUFFED SLEEVES SHIRT DRESS</h2>
                        <span class="price">$655</span>
                    </div>
                    <div class="collection-carousel-card" id="2" onclick="location.href='#';">
                        <img src="{% static 'images/card21.jpg' %}" alt="" >
                        <h2>SIDE PLEATS LONG JACKET</h2>
                        <span class="price">$853</span>
                    </div>
                    <div class="collection-carousel-card" id="3" onclick="location.href='#';">
                        <img src="{% static 'images/card31.jpg' %}" alt="" >
                        <h2>COTTON KAFTAN DRESS</h2>
                        <span class="price">$589</span>
                    </div>
                    <div class="collection-carousel-card" id="4" onclick="location.href='#';">
                        <img src="{% static 'images/card41.jpg' %}" alt="" >
                        <h2>CONTRASTED LOOSE LONG CARDIGAN</h2>
                        <span class="price">$671</span>
                    </div>

                    <div class="collection-carousel-card" id="5" onclick="location.href='#';">
                        <img src="{% static 'images/card11.jpg' %}" alt="">
                        <h2>COTTON PUFFED SLEEVES SHIRT DRESS</h2>
                        <span class="price">$655</span>
                    </div>
 


                </div>
                
            </div>
            <div class="next-button right-button">
                <i class="far fa-chevron-right"></i>
            </div>
        </div>  
    </div>    

    <div class="shop-collection">
        <a href="#">SHOP THE COLLECTION</a>
    </div>
{% endblock content %}


{% block scripts %}
    <script src="{% static 'scripts/script.js' %}"></script>
    <script src="{% static 'scripts/cart.js' %}"></script>
    <script src="{% static 'scripts/mobilemenu.js' %}"></script>
{% endblock scripts %}

templates/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Login
{% endblock title %}


{% block content %}
    <!---------------------------------------------Login------------------------------------------------->


    <div class="login" id="login">
        <div class="login-head">
            <h2>LOGIN</h2>
            <p>Please enter your e-mail and password:</p>
        </div>
        <div class="login-form">
            <form action="" method="POST">
                <!-- <input type="text" name="email" placeholder="Email" autocomplete="off">
                <input type="password" name="password" placeholder="Password"> -->
                {% csrf_token %}
                {{ form.as_p }}
                <div id="forgot"><span>Forgot your password?</span></div>
                <button type="submit">LOGIN</button>
            </form>
        </div>
        <div class="login-signup">
            <p>Don't have an account? <a href="{% url 'account:register' %}">Create One</a></p>
        </div>
    </div>
 
    <div class="login" id="recover">
        <div class="login-head">
            <h2>RECOVER PASSWORD</h2>
            <p>Please enter your email:</p>
        </div>
        <div class="login-form">
            <form action="" method="POST">
                <input type="email" name="email" placeholder="Email" autocomplete="off">
                <button type="submit">RECOVER</button>
            </form>
        </div>
        <div class="login-signup">
            <p>Remember your password? <a href="#">Back to Login</a></p>
        </div>
    </div>

{% endblock content %}

{% block scripts %}
    <script src="{% static 'scripts/login.js' %}"></script>
    <script src="{% static 'scripts/cart.js' %}"></script>
    <script src="{% static 'scripts/mobilemenu.js' %}"></script>
{% endblock scripts %}